name: Terraform AWS Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-deploy:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:

      # ======================================================
      # 1. DESCARGAR REPOSITORIO
      # ======================================================
      - name: Checkout
        uses: actions/checkout@v4


      # ======================================================
      # 2. AUTENTICACION AWS MEDIANTE OIDC
      # ======================================================
      - name: Autenticarse en AWS
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::014668143169:role/devops-juan
          aws-region: us-east-1


      # ======================================================
      # 3. VERIFICAR IDENTIDAD AWS
      # ======================================================
      - name: Verificar identidad AWS
        run: aws sts get-caller-identity
        working-directory: .


      # ======================================================
      # 4. INSTALAR TERRAFORM
      # ======================================================
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8


      # ======================================================
      # 5. TERRAFORM INIT
      # ======================================================
      - name: Terraform Init
        run: terraform init


      # ======================================================
      # 6. TERRAFORM FORMAT
      # ======================================================
      - name: Terraform Format
        run: terraform fmt -check


      # ======================================================
      # 7. TERRAFORM VALIDATE
      # ======================================================
      - name: Terraform Validate
        run: terraform validate


      # ======================================================
      # 8. TERRAFORM PLAN
      # Guarda el plan en tfplan
      # ======================================================
      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan


      # ======================================================
      # 9. TERRAFORM APPLY
      # Aplica exactamente el plan anterior
      # ======================================================
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan


      # ======================================================
      # 10. MOSTRAR OUTPUTS
      # ======================================================
      - name: Terraform Outputs
        run: terraform output